import { useMemo, useState } from 'react'
import { ArrowLeft, ChevronDown, FileCheck2, Lightbulb, ShieldCheck, Target } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Badge } from '../components/Badge'
import { SectionCard } from '../components/SectionCard'
import { ScoreRing } from '../components/ScoreRing'
import { SkillPill } from '../components/SkillPill'
import type { Analysis, Report } from '../types'
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts'

const labels: Record<string, string> = {
  required_skills: 'Required skills',
  preferred_skills: 'Preferred skills',
  semantic_relevance: 'Semantic relevance',
  experience_alignment: 'Experience alignment',
  project_relevance: 'Project relevance',
}

function scoreTone(score: number): 'green' | 'amber' | 'red' { return score >= 75 ? 'green' : score >= 55 ? 'amber' : 'red' }

function MatchSummary({ report }: { report: Report }) {
  const chartData = Object.entries(report.score_components).map(([key, value]) => ({ name: labels[key] || key, score: value.contribution, full: value.weight }))
  return (
    <SectionCard title="Resume vs Job Match" eyebrow="Overall assessment">
      <div className="flex flex-col items-center gap-7 lg:flex-row lg:items-center">
        <ScoreRing score={report.overall_score} />
        <div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><Badge tone={scoreTone(report.overall_score)}>{report.overall_score >= 75 ? 'Strong alignment' : report.overall_score >= 55 ? 'Moderate alignment' : 'Needs attention'}</Badge><Badge tone="slate">Evidence-based</Badge></div><p className="mt-3 text-sm leading-6 text-slate-600">The score is a weighted combination of skills, semantic relevance, experience, and project relevance. The LLM does not determine this score.</p><div className="mt-5 overflow-hidden rounded-xl border border-slate-200"><div className="h-2 bg-slate-100"><div className="h-full rounded-full bg-slate-900" style={{ width: `${report.overall_score}%` }} /></div><div className="grid gap-0 divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-5">{chartData.map((item) => <div key={item.name} className="p-3"><p className="text-[11px] font-semibold leading-4 text-slate-500">{item.name}</p><p className="mt-1 text-sm font-black text-slate-900">{item.score}/{item.full}</p></div>)}</div></div></div>
      </div>
      <div className="mt-7 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} layout="vertical" margin={{ left: 18, right: 12, top: 8, bottom: 8 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" /><XAxis type="number" domain={[0, 40]} hide /><YAxis type="category" dataKey="name" width={135} tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => [`${value} points`, 'Contribution']} /><Bar dataKey="score" fill="#0f172a" radius={[0, 6, 6, 0]} barSize={17} /></BarChart></ResponsiveContainer></div>
    </SectionCard>
  )
}

function EvidenceList({ report }: { report: Report }) {
  const [tab, setTab] = useState<'matched' | 'partial' | 'missing'>('matched')
  const data = tab === 'matched' ? report.matched_skills : tab === 'partial' ? report.partial_skills : report.missing_skills
  return <SectionCard title="Skill Breakdown" eyebrow="Normalized skill matching"><div className="mb-4 flex flex-wrap gap-2">{(['matched', 'partial', 'missing'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-3 py-2 text-xs font-bold capitalize transition ${tab === item ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{item} ({item === 'matched' ? report.skill_summary.matched_count : item === 'partial' ? report.skill_summary.partial_count : report.skill_summary.missing_count})</button>)}</div>{data.length ? <div className="grid gap-3 md:grid-cols-2">{data.map((item) => <SkillPill key={item.skill} item={item} />)}</div> : <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No items in this category.</p>}</SectionCard>
}

export function ResultsPage() {
  const location = useLocation()
  const navigate = useNavigate()
  const analysis = location.state as Analysis | null
  const report = analysis?.report
  const preferredMatched = useMemo(() => report?.preferred_skills.filter((x) => x.matched) ?? [], [report])

  if (!analysis || !report) return <div className="mx-auto max-w-xl py-20 text-center"><h1 className="text-2xl font-black">Report not found</h1><p className="mt-2 text-slate-500">Run a fresh analysis from the matcher page.</p><button onClick={() => navigate('/')} className="mt-6 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Back to matcher</button></div>

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={() => navigate('/')} className="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={15} /> New analysis</button><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Analysis report</p><h1 className="mt-1 text-3xl font-black tracking-tight">{analysis.job_title || 'Resume vs Job Match'}</h1><p className="mt-2 text-sm text-slate-500">{analysis.resume_name}{analysis.company_name ? ` · ${analysis.company_name}` : ''}{analysis.demo ? ' · Demo mode' : ''}</p></div><div className="flex items-center gap-2"><Badge tone="blue"><ShieldCheck size={13} className="mr-1" /> No resume file stored</Badge><Badge tone="slate">{report.semantic_evidence.resume_to_jd_similarity}% semantic similarity</Badge></div></div>

      <MatchSummary report={report} />

      <div className="grid gap-3 sm:grid-cols-3">
        <div className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Strong matches</p><p className="mt-2 text-3xl font-black text-emerald-900">{report.skill_summary.matched_count}</p><p className="mt-1 text-xs text-emerald-800/70">Required skills with direct resume evidence.</p></div>
        <div className="rounded-2xl border border-amber-200 bg-amber-50/60 p-4"><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Partial matches</p><p className="mt-2 text-3xl font-black text-amber-900">{report.skill_summary.partial_count}</p><p className="mt-1 text-xs text-amber-800/70">Semantically related evidence, not a direct normalized hit.</p></div>
        <div className="rounded-2xl border border-rose-200 bg-rose-50/60 p-4"><p className="text-xs font-bold uppercase tracking-wider text-rose-700">Skill gaps</p><p className="mt-2 text-3xl font-black text-rose-900">{report.skill_summary.missing_count}</p><p className="mt-1 text-xs text-rose-800/70">Required skills without supporting resume evidence.</p></div>
      </div>

      <div className="grid gap-5 xl:grid-cols-2"><EvidenceList report={report} /><SectionCard title="Job Requirements" eyebrow="What the JD asks for"><div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Required</p><div className="mt-2 flex flex-wrap gap-2">{report.job_requirements.required_skills.map((s) => <Badge key={s} tone="blue">{s}</Badge>)}</div></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Preferred</p><div className="mt-2 flex flex-wrap gap-2">{report.job_requirements.preferred_skills.length ? report.job_requirements.preferred_skills.map((s) => <Badge key={s} tone="amber">{s}</Badge>) : <span className="text-sm text-slate-500">None detected.</span>}</div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Education</p><p className="mt-2 text-sm font-semibold text-slate-700">{report.job_requirements.education_requirements.join(', ') || 'Not detected'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Experience</p><p className="mt-2 text-sm font-semibold text-slate-700">{report.job_requirements.experience_years ? `${report.job_requirements.experience_years}+ years` : 'Not specified'}</p></div></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Soft skills</p><div className="mt-2 flex flex-wrap gap-2">{report.job_requirements.soft_skills.map((s) => <Badge key={s} tone="slate">{s}</Badge>)}{!report.job_requirements.soft_skills.length && <span className="text-sm text-slate-500">None detected.</span>}</div></div></div></SectionCard></div>

      <div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Project Relevance" eyebrow="Project-to-JD alignment">{report.project_relevance.length ? <div className="space-y-3">{report.project_relevance.map((project) => <div key={project.name} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold">{project.name}</p><div className="mt-1 flex flex-wrap gap-1.5">{project.reasons.map((reason) => <span key={reason} className="text-xs text-slate-500">• {reason}</span>)}</div></div><Badge tone={project.level === 'High' ? 'green' : project.level === 'Medium' ? 'amber' : 'slate'}>{project.level} · {project.relevance_score}%</Badge></div>{project.evidence && <p className="mt-3 text-xs leading-5 text-slate-600">Evidence: “{project.evidence}”</p>}</div>)}</div> : <p className="text-sm text-slate-500">No projects were detected in the resume.</p>}</SectionCard><SectionCard title="Experience Alignment" eyebrow="Duration and context"><div className="flex items-center gap-5"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-slate-900 text-xl font-black text-white">{report.experience_alignment.score}%</div><div><p className="text-sm font-bold text-slate-900">{report.experience_alignment.resume_years ?? 0} year(s) detected vs {report.experience_alignment.required_years ?? 'no'} required</p><p className="mt-1 text-sm leading-6 text-slate-500">{report.experience_alignment.explanation}</p></div></div></SectionCard></div>

      <div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Skill Gap Analysis" eyebrow="Priority gaps"><div className="space-y-4"><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-bold">High-priority gaps</p><Badge tone="red">{report.skill_gap_analysis.high_priority.length}</Badge></div>{report.skill_gap_analysis.high_priority.length ? <div className="space-y-2">{report.skill_gap_analysis.high_priority.map((gap) => <div key={gap.skill} className="rounded-xl border border-rose-200 bg-rose-50/60 p-3"><p className="text-sm font-bold text-rose-900">{gap.skill}</p><p className="mt-1 text-xs leading-5 text-rose-800/80">{gap.why_it_matters}</p></div>)}</div> : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No high-priority gaps detected.</p>}</div><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-bold">Low-priority gaps</p><Badge tone="amber">{report.skill_gap_analysis.low_priority.length}</Badge></div>{report.skill_gap_analysis.low_priority.length ? <div className="space-y-2">{report.skill_gap_analysis.low_priority.map((gap) => <div key={gap.skill} className="rounded-xl border border-amber-200 bg-amber-50/60 p-3"><p className="text-sm font-bold text-amber-900">{gap.skill}</p><p className="mt-1 text-xs leading-5 text-amber-800/80">{gap.why_it_matters}</p></div>)}</div> : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No low-priority gaps detected.</p>}</div></div></SectionCard><SectionCard title="Resume Improvement Suggestions" eyebrow="Actionable and evidence-grounded"><div className="space-y-3">{report.recommendations.map((rec, index) => <details key={`${rec.action}-${index}`} className="group rounded-xl border border-slate-200"><summary className="flex cursor-pointer list-none items-center gap-3 p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-sky-50 text-sky-600"><Lightbulb size={15} /></span><span className="flex-1 text-sm font-bold">{rec.action}</span><ChevronDown size={16} className="text-slate-400 transition group-open:rotate-180" /></summary><div className="border-t border-slate-100 px-4 pb-4 pt-3"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Why this appears</p><p className="mt-1 text-sm leading-6 text-slate-600">{rec.basis}</p>{rec.evidence && <p className="mt-2 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">Evidence / basis: {rec.evidence}</p>}</div></details>)}</div></SectionCard></div>

      <SectionCard title="Detailed Evidence" eyebrow="What the parser found"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><FileCheck2 size={17} className="text-sky-600" /><p className="font-bold">Resume profile</p></div><div className="mt-4 flex flex-wrap gap-2">{[...report.resume_analysis.technical_skills, ...preferredMatched.map((x) => x.skill)].slice(0, 24).map((skill) => <Badge key={skill} tone="slate">{skill}</Badge>)}</div><p className="mt-4 text-sm leading-6 text-slate-500">Education: {report.resume_analysis.education.text || 'Not detected.'}</p><p className="mt-2 text-sm leading-6 text-slate-500">Experience: {report.resume_analysis.experience.text || 'Not detected.'}</p></div><div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><Target size={17} className="text-emerald-600" /><p className="font-bold">Recommendation basis</p></div><div className="mt-4 space-y-2">{report.recommendations.slice(0, 6).map((rec, i) => <p key={i} className="text-sm leading-6 text-slate-600"><span className="font-bold text-slate-900">{i + 1}.</span> {rec.basis}</p>)}</div></div></div>{report.llm_enrichment?.executive_summary && <div className="mt-5 rounded-2xl bg-slate-900 p-5 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">AI summary</p><p className="mt-2 text-sm leading-7 text-slate-200">{report.llm_enrichment.executive_summary}</p></div>}</SectionCard>
    </div>
  )
}
